<?php

return [
    [
        'code' => 'service_formalite',
        'numero' => 'II.3.1',
        'nom' => 'Service Accueil et Formalités',
        'icon' => 'fa-file-signature',
        'intro' => 'Le Service Accueil et Formalités a pour attributions de :',
        'resume' => 'Accueil des pensionnés, cartes de pension, mandats, virements et visites à domicile.',
        'attributions' => [
            'Accueillir les nouveaux pensionnés et les orienter dans les différents services de la DPC pour d’autres suivis.',
            'Préparer les cartes de pension.',
            'Recevoir et valider les mandats (consulaires ou locaux) livrés par les pensionnés aux mandataires.',
            'Encadrer les bénéficiaires encore mineurs et les handicapés mentaux accompagnés de leurs tuteurs ou subrogés tuteurs.',
            'Procéder, à chaque début d’exercice, aux suivis nécessaires pour la mise à jour des dossiers des pensionnés.',
            'S’occuper des pensionnés mineurs, ceux qui ont moins de vingt-cinq (25) ans et des pensionnés déficients physiquement et/ou mentalement.',
            'Se charger des pensionnés qui ne peuvent se déplacer parce qu’ils sont frappés par un handicap quelconque, en se rendant chez le pensionné pour lui faire remplir le formulaire ou pour lui apporter sa lettre d’attestation quand il doit voir un médecin. Ce service est appelé « service de proximité » ou « visite domiciliaire ».',
            'S’occuper des virements bancaires pour les pensionnés qui préfèrent recevoir leur cotisation directement à la banque ; ils peuvent en faire la demande en remplissant un formulaire spécial.',
        ],
    ],
    [
        'code' => 'service_liquidation',
        'numero' => 'II.3.2',
        'nom' => 'Service de Liquidation',
        'icon' => 'fa-file-invoice-dollar',
        'intro' => 'Le Service de Liquidation a pour attributions de (d’) :',
        'resume' => 'Traitement des dossiers et établissement du droit à la pension civile.',
        'attributions' => [
            'S’occuper du traitement, du classement, de l’enregistrement des dossiers, de la mise à jour des fiches électroniques des pétitionnaires.',
            'Gérer les comptes des organismes autonomes affiliés et leur fournir un rapport à chaque début d’exercice.',
            'Établir le droit à la pension suivant les prescrits du décret régissant la pension civile de retraite.',
        ],
    ],
    [
        'code' => 'service_comptabilite',
        'numero' => 'II.3.3',
        'nom' => 'Service de la Comptabilité',
        'icon' => 'fa-calculator',
        'intro' => 'Le Service de la Comptabilité a pour attributions de (d’) :',
        'resume' => 'Payroll, paiements, chèques et suivi des doléances des pensionnés.',
        'attributions' => [
            'Enregistrer sur le payroll de la pension civile les nouveaux pensionnés publiés au journal officiel de la République, Le Moniteur.',
            'Traiter les réversibilités.',
            'Préparer le payroll mensuel.',
            'Recevoir les doléances des pensionnés et les traiter dans leurs différents aspects.',
            'Distribuer les chèques aux pensionnés de Port-au-Prince et ses environs.',
            'Expédier les chèques, plis séparés et correspondances vers les villes de province.',
            'Assurer le suivi des différentes requêtes de la DPC auprès des autres directions du MEF.',
            'Inventorier les chèques en main, annuler et retourner les chèques prescrits.',
        ],
    ],
    [
        'code' => 'service_assurance',
        'numero' => 'II.3.4',
        'nom' => 'Service Assurance',
        'icon' => 'fa-shield-alt',
        'intro' => 'Le Service Assurance a pour attributions de (d’) :',
        'resume' => 'Couverture d’assurance maladie et contribution funéraire des pensionnés.',
        'attributions' => [
            'S’occuper de toutes les démarches liées à la couverture d’assurance des pensionnés afin de leur permettre de bénéficier du remboursement des soins de santé.',
            'S’assurer de l’octroi de la contribution funéraire en cas de décès d’un pensionné.',
        ],
    ],
    [
        'code' => 'service_archives',
        'numero' => 'II.3.5',
        'nom' => 'Service des Archives',
        'icon' => 'fa-box-archive',
        'intro' => 'Le Service des Archives a pour attribution d’archiver les correspondances, les fichiers de demande de pension et les dossiers de chaque pensionné.',
        'resume' => 'Archivage des correspondances, des demandes et des dossiers des pensionnés.',
        'attributions' => [],
    ],
    [
        'code' => 'cellule_administration',
        'numero' => 'II.3.6',
        'nom' => 'Service Administratif',
        'icon' => 'fa-user-cog',
        'intro' => 'Le Service Administratif a pour attributions de (d’) :',
        'resume' => 'Matériel, logistique, entretien et appui à la gestion des ressources humaines.',
        'attributions' => [
            'Pourvoir en matériel et équipement les différents services de la DPC.',
            'Assurer les services de transport et logistique.',
            'Veiller à l’entretien général du bâtiment.',
            'Assister la Direction dans la gestion des ressources humaines.',
        ],
    ],
    [
        'code' => 'service_controle_placement',
        'numero' => 'II.3.7',
        'nom' => 'Service de Contrôle et Placement',
        'icon' => 'fa-search',
        'intro' => 'Le Service de Contrôle et Placement a pour attributions de (d’) :',
        'resume' => 'Sûreté des opérations financières, placements et suivi du patrimoine.',
        'attributions' => [
            'Veiller à l’adéquation et à la sûreté des opérations financières.',
            'Chercher et étudier des possibilités de placement.',
            'Assurer le suivi des opérations de placements et de prêts.',
            'Rendre compte des opérations financières affectant le compte pension civile et du patrimoine de la Pension Civile.',
        ],
    ],
];
