<?php

namespace App\Enums;

enum TypeDemandeEnum: string
{
    // PENSIONNAIRE
    case DEMANDE_VIREMENT_BANCAIRE = 'DEMANDE_VIREMENT_BANCAIRE';
    case DEMANDE_ATTESTATION = 'DEMANDE_ATTESTATION';
    case DEMANDE_TRANSFERT_CHEQUE = 'DEMANDE_TRANSFERT_CHEQUE';
    case DEMANDE_ARRET_PAIEMENT = 'DEMANDE_ARRET_PAIEMENT';
    case DEMANDE_REINSERTION = 'DEMANDE_REINSERTION';
    case DEMANDE_ARRET_VIREMENT = 'DEMANDE_ARRET_VIREMENT';
    case DEMANDE_PREUVE_EXISTENCE = 'DEMANDE_PREUVE_EXISTENCE';
    case DEMANDE_PENSION_REVERSION = 'DEMANDE_PENSION_REVERSION';

    // FONCTIONNAIRE
    case DEMANDE_ETAT_CARRIERE = 'DEMANDE_ETAT_CARRIERE';
    case DEMANDE_PENSION = 'DEMANDE_PENSION';

    // INSTITUTION
    case DEMANDE_ADHESION = 'DEMANDE_ADHESION';
}